// <auto-generated />
namespace TestShenzhenWebApplication.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updateissueproductmpstring : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateissueproductmpstring));
        
        string IMigrationMetadata.Id
        {
            get { return "201508301448549_update-issue-product-mp-string"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
