// <auto-generated />
namespace TestShenzhenWebApplication.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addissuemodelfeatureupdatename : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addissuemodelfeatureupdatename));
        
        string IMigrationMetadata.Id
        {
            get { return "201508301251000_add-issue-model-feature-update-name"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
