// <auto-generated />
namespace TestShenzhenWebApplication.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class addtaglunchtoreg : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addtaglunchtoreg));
        
        string IMigrationMetadata.Id
        {
            get { return "201511011558089_add-tag-lunch-to-reg"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
