// <auto-generated />
namespace TestShenzhenWebApplication.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class addadminusermodelupdate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addadminusermodelupdate));
        
        string IMigrationMetadata.Id
        {
            get { return "201509061426571_add-admin-user-model-update"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
