// <auto-generated />
namespace TestShenzhenWebApplication.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class issueupdatefromremove4g : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(issueupdatefromremove4g));
        
        string IMigrationMetadata.Id
        {
            get { return "201508310823238_issue-update-from-remove-4g"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
